import R from 'ramda'

export const playingPath = R.lensPath(['playing'])
export const bpmPath = R.lensPath(['bpm'])
export const volumePath = R.lensPath(['volume'])
export const masterVolumePath = R.compose(volumePath, R.lensPath(['master']))
export const accentVolumePath = R.compose(volumePath, R.lensPath(['accent']))
export const quarterVolumePath = R.compose(volumePath, R.lensPath(['quarter']))
export const eighthVolumePath = R.compose(volumePath, R.lensPath(['eighth']))
export const sixteenthVolumePath = R.compose(volumePath, R.lensPath(['sixteenth']))
export const tripletVolumePath = R.compose(volumePath, R.lensPath(['triplet']))
export const beatPath = R.lensPath(['beat'])
export const showTimeSignatureSettingsPath = R.lensPath(['show time sig sets'])
export const stylePath = R.lensPath(['styles my man'])
export const styleBeatsPath = R.lensPath(['style beats, my man'])
export const styleIndexPath = R.lensPath(['style index'])
export const editingBPMPath = R.lensPath(['editing bpm'])
export const keymapPath = R.lensPath(['keymap path'])
export const versionPath = R.lensPath(['version path'])
export const audioContextPath = R.lensPath(['audioContext'])
export const masterMutePath = R.lensPath(['masterMutePath'])
export const accentMutePath = R.lensPath(['accentMutePath'])
export const quarterMutePath = R.lensPath(['quarterMutePath'])
export const eighthMutePath = R.lensPath(['eighthMutePath'])
export const sixteenthMutePath = R.lensPath(['sixteenthMutePath'])
export const tripletMutePath = R.lensPath(['tripletMutePath'])
export const newContentAvailablePath = R.lensPath(['new content available'])
